// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjQbMtlo_Tt6GxS4iVYy7YII85n-R36LY',
    appId: '1:456838549894:web:56c1068003fd8b6c9c9c07',
    messagingSenderId: '456838549894',
    projectId: 'todo-21d0a',
    authDomain: 'todo-21d0a.firebaseapp.com',
    storageBucket: 'todo-21d0a.appspot.com',
    measurementId: 'G-LC2Q8CFHYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJVGQUDrczFuQOERlMoDSKgt4W4A9NyKQ',
    appId: '1:456838549894:android:2c66c86f2bf383099c9c07',
    messagingSenderId: '456838549894',
    projectId: 'todo-21d0a',
    storageBucket: 'todo-21d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADuHTuIu-E_pl0oPzuyx0D-oQTGKS-Rjo',
    appId: '1:456838549894:ios:b64f28c9a2f480eb9c9c07',
    messagingSenderId: '456838549894',
    projectId: 'todo-21d0a',
    storageBucket: 'todo-21d0a.appspot.com',
    iosClientId: '456838549894-o2osegpn5btodmln28amofetrdlek865.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADuHTuIu-E_pl0oPzuyx0D-oQTGKS-Rjo',
    appId: '1:456838549894:ios:b64f28c9a2f480eb9c9c07',
    messagingSenderId: '456838549894',
    projectId: 'todo-21d0a',
    storageBucket: 'todo-21d0a.appspot.com',
    iosClientId: '456838549894-o2osegpn5btodmln28amofetrdlek865.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebase',
  );
}
